spring.application.name=code-recognizer

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.port=8080

barcode.apis.OpenFoodFacts=https://world.openfoodfacts.org/api/v0/product/%s.json
barcode.apis.UPCItemDB=https://api.upcitemdb.com/prod/trial/lookup?upc=%s
barcode.apis.Datakick=https://www.gtinsearch.org/api/items/%s
barcode.apis.OpenBeautyFacts=https://world.openbeautyfacts.org/api/v0/product/%s

logging.level.com.example.coderecognizer=DEBUG